-- Create pipeline_automacoes table
CREATE TABLE IF NOT EXISTS pipeline_automacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT REFERENCES pipelines(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    gatilho TEXT NOT NULL CHECK (gatilho IN ('stage_change')),
    gatilho_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    acao_tipo TEXT NOT NULL CHECK (acao_tipo IN ('email', 'webhook', 'whatsapp', 'task')),
    acao_config JSONB NOT NULL DEFAULT '{}'::jsonb,
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create pipeline_automacao_logs table
CREATE TABLE IF NOT EXISTS pipeline_automacao_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    automacao_id BIGINT REFERENCES pipeline_automacoes(id) ON DELETE SET NULL,
    lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    details JSONB,
    executed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE pipeline_automacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_automacao_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies for pipeline_automacoes
CREATE POLICY "Enable read access for authenticated users" ON pipeline_automacoes
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable insert access for authenticated users" ON pipeline_automacoes
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update access for authenticated users" ON pipeline_automacoes
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete access for authenticated users" ON pipeline_automacoes
    FOR DELETE TO authenticated USING (true);

-- RLS Policies for pipeline_automacao_logs
CREATE POLICY "Enable read access for authenticated users" ON pipeline_automacao_logs
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable insert access for authenticated users" ON pipeline_automacao_logs
    FOR INSERT TO authenticated WITH CHECK (true);
